name: Beta
description: Beta
title: "Beta"
labels: ["beta"]
body:
  - type: markdown
    attributes:
      value: Issue will be moved to another repo
 - type: label
   attributes:
    value: What's the issue?
