name: Transfer Issue & Create Stub
on:
  issues:
    types: [opened, labeled]

jobs:
  beta:
    runs-on: ubuntu-latest
    name: Job to transfer issue to private repo
    steps:
    - name: Transfer Issue & Create Stub
      uses: lando/transfer-issue-action@v2
      with:
        token: ${{ secrets.BETA_TOKEN }}
        router: beta:private-issue-repo-tes
        apply_label: "beta request"
        create_stub: false